[package]
name = "lovely"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
pretty_assertions = "1.4.1"

[dev-dependencies]
insta = { version = "1.43.1", features = ["glob"] }
